### ISSUE TITLE
Remove tmp files when preparing data

### ISSUE THREAD

**Issue by mpdprot** [LPDI-EPFL/masif#22]
MSMS, for example, is leaving huge files in the tmp directory. These should be removed.

**Comment by pablogainza** [comment]
Hi !! Sorry for the late reply. 
I've made the fixes you suggested. Thank you so much for pointing it out. I don't remove the pdbs themselves because it is sometimes useful to have them in the tmp directory but I do remove the MSMS and APBS temporary files which are also the bulkiest. 

Thanks !!
Pablo

**Comment by mpdprot** [comment]
Ah very good, thanks!
