### ISSUE TITLE
step 1 download pdf failed

### ISSUE THREAD

**Issue by billryan** [LPDI-EPFL/masif#3]
When I run `./data_prepare_one.sh 1MBN_A_` under `data/masif_site`, it failed to download and showed
```
WARNING: The default download format has changed from PDB to PDBx/mmCif
```

**Comment by jaumebonet** [comment]
@pablogainza, @FreyrS seems that there is a newer version of biopython than the one used in the repo and (at least) the [retrieve_pdb_file](https://biopython.org/DIST/docs/api/Bio.PDB.PDBList%27.PDBList-class.html#retrieve_pdb_file) function has been updated. 

The fix should be as easy as add `file_format='pdb'` to the call to `retrieve_pdb_file` in `source/data_preparation/00-pdb_download.py`. 

One should avoid this by adding fixed versions in the `requirement.txt` file, so that one won't need to keep updating the code at each update of each dependent library.

**Comment by pablogainza** [comment]
Thanks Jaume!!

Billyryan, I am also working on a docker container with MaSIF for easy
reproduction of the results. I hope to have it on a week or two.
